// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { unwrapWebhook } = require('../utils');

const EVENT = "appointment/cancelled";

const performSubscribe = async (z, bundle) => {
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/subscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: bundle.targetUrl },
  });
  return { ...(response.data || {}), event: EVENT, target_url: bundle.targetUrl };
};

const performUnsubscribe = async (z, bundle) => {
  const sub = bundle.subscribeData || {};
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/unsubscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: sub.target_url },
  });
  return response.data;
};

// Inbound webhook delivery: [{ entity_name, event_type, data }] -> data objects.
const perform = (z, bundle) => unwrapWebhook(bundle.cleanedRequest);

// No "recent events" endpoint exists, so the captured sample is the fallback
// users see when pulling a sample during Zap setup.
const sample = {
  "business_id": "j9q05nvfv12w79vl",
  "appointment_id": "3in0a3b32nut67l6",
  "conversation_id": "pto6yng4e908c8g0",
  "title": "Introductory Phone Call",
  "client_id": "54gjvtadfbxiom7y",
  "staff_id": "e6j4i1ofy2pf0dmg",
  "start_time": "2019-10-29T10:00:00.000+02:00",
  "end_time": "2019-10-29T10:30:00.000+02:00",
  "duration": 30,
  "service_uid": "02nbrfqxys1gmoj2",
  "notes": "",
  "interaction_details": "123456",
  "currency": "ILS",
  "payment_id": null,
  "where": "phone",
  "source_data": {
    "id": 215954943,
    "name": "initiated_by_staff",
    "channel": null,
    "campaign": null,
    "website_url": null
  }
};
const performList = async () => [sample];

const outputFields = [
  {
    "key": "business_id",
    "label": "Business Id",
    "type": "string"
  },
  {
    "key": "appointment_id",
    "label": "Appointment Id",
    "type": "string"
  },
  {
    "key": "conversation_id",
    "label": "Conversation Id",
    "type": "string"
  },
  {
    "key": "title",
    "label": "Title",
    "type": "string"
  },
  {
    "key": "client_id",
    "label": "Client Id",
    "type": "string"
  },
  {
    "key": "staff_id",
    "label": "Staff Id",
    "type": "string"
  },
  {
    "key": "start_time",
    "label": "Start Time",
    "type": "string"
  },
  {
    "key": "end_time",
    "label": "End Time",
    "type": "string"
  },
  {
    "key": "duration",
    "label": "Duration",
    "type": "number"
  },
  {
    "key": "service_uid",
    "label": "Service Uid",
    "type": "string"
  },
  {
    "key": "notes",
    "label": "Notes",
    "type": "string"
  },
  {
    "key": "interaction_details",
    "label": "Interaction Details",
    "type": "string"
  },
  {
    "key": "currency",
    "label": "Currency",
    "type": "string"
  },
  {
    "key": "payment_id",
    "label": "Payment Id",
    "type": "string"
  },
  {
    "key": "where",
    "label": "Where",
    "type": "string"
  },
  {
    "key": "source_data",
    "label": "Source Data",
    "type": "string"
  }
];

module.exports = {
  key: "appointment_cancelled",
  noun: "Appointment",
  display: {
    label: "New Appointment (appointment/cancelled)",
    description: "Triggers when a vcita \"appointment/cancelled\" webhook fires.",
  },
  operation: {
    type: 'hook',
    performSubscribe,
    performUnsubscribe,
    perform,
    performList,
    sample,
    outputFields,
  },
};
