// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { unwrapWebhook } = require('../utils');

const EVENT = "invoice/issued";

const performSubscribe = async (z, bundle) => {
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/subscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: bundle.targetUrl },
  });
  return { ...(response.data || {}), event: EVENT, target_url: bundle.targetUrl };
};

const performUnsubscribe = async (z, bundle) => {
  const sub = bundle.subscribeData || {};
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/unsubscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: sub.target_url },
  });
  return response.data;
};

// Inbound webhook delivery: [{ entity_name, event_type, data }] -> data objects.
const perform = (z, bundle) => unwrapWebhook(bundle.cleanedRequest);

// No "recent events" endpoint exists, so the captured sample is the fallback
// users see when pulling a sample during Zap setup.
const sample = {
  "business_id": "s5ek7tfgp068i2st",
  "staff_id": "e6j4i1ofy2pf0dmg",
  "conversation_id": "pto6yng4e908c8g0",
  "invoice_id": "ujjq3chk5jv91y0q",
  "state": "issued",
  "title": "#0000001",
  "issued_at": "2019-10-29",
  "due_date": "2019-11-28",
  "invoice_number": 1,
  "address": "Tel Aviv",
  "note": null,
  "amount": "35.84",
  "currency": "ILS",
  "charge_at": null,
  "client_id": "54gjvtadfbxiom7y",
  "created_at": "2019-10-29T09:33:43.000+02:00",
  "items": [
    {
      "title": "Demo Class / Event",
      "amount": "35.84",
      "tax": "3.84"
    }
  ]
};
const performList = async () => [sample];

const outputFields = [
  {
    "key": "business_id",
    "label": "Business Id",
    "type": "string"
  },
  {
    "key": "staff_id",
    "label": "Staff Id",
    "type": "string"
  },
  {
    "key": "conversation_id",
    "label": "Conversation Id",
    "type": "string"
  },
  {
    "key": "invoice_id",
    "label": "Invoice Id",
    "type": "string"
  },
  {
    "key": "state",
    "label": "State",
    "type": "string"
  },
  {
    "key": "title",
    "label": "Title",
    "type": "string"
  },
  {
    "key": "issued_at",
    "label": "Issued At",
    "type": "string"
  },
  {
    "key": "due_date",
    "label": "Due Date",
    "type": "string"
  },
  {
    "key": "invoice_number",
    "label": "Invoice Number",
    "type": "number"
  },
  {
    "key": "address",
    "label": "Address",
    "type": "string"
  },
  {
    "key": "note",
    "label": "Note",
    "type": "string"
  },
  {
    "key": "amount",
    "label": "Amount",
    "type": "string"
  },
  {
    "key": "currency",
    "label": "Currency",
    "type": "string"
  },
  {
    "key": "charge_at",
    "label": "Charge At",
    "type": "string"
  },
  {
    "key": "client_id",
    "label": "Client Id",
    "type": "string"
  },
  {
    "key": "created_at",
    "label": "Created At",
    "type": "string"
  },
  {
    "key": "items",
    "label": "Items",
    "type": "string"
  }
];

module.exports = {
  key: "invoice_issued",
  noun: "Invoice",
  display: {
    label: "New Invoice (invoice/issued)",
    description: "Triggers when a vcita \"invoice/issued\" webhook fires.",
  },
  operation: {
    type: 'hook',
    performSubscribe,
    performUnsubscribe,
    perform,
    performList,
    sample,
    outputFields,
  },
};
