// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField, resolveMatterUid, setByPath } = require('../utils');

const PATH = "/business/scheduling/v1/appointments";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "client_id",
    "path": [
      "client_id"
    ],
    "label": "Client",
    "type": "string",
    "required": true,
    "isJson": false,
    "dynamic": "list_clients.id.label"
  },
  {
    "key": "service_id",
    "path": [
      "service_id"
    ],
    "label": "Service",
    "type": "string",
    "required": true,
    "isJson": false,
    "dynamic": "list_services.id.label"
  },
  {
    "key": "staff_id",
    "path": [
      "staff_id"
    ],
    "label": "Staff",
    "type": "string",
    "required": true,
    "isJson": false,
    "dynamic": "list_staff.id.label"
  },
  {
    "key": "title",
    "path": [
      "title"
    ],
    "label": "Title",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Appointment title (defaults to the service name)"
  },
  {
    "key": "start_time",
    "path": [
      "start_time"
    ],
    "label": "Start Time",
    "type": "datetime",
    "required": true,
    "isJson": false,
    "helpText": "ISO 8601, business-local time"
  },
  {
    "key": "end_time",
    "path": [
      "end_time"
    ],
    "label": "End Time",
    "type": "datetime",
    "required": true,
    "isJson": false,
    "helpText": "ISO 8601; default start + service duration"
  },
  {
    "key": "interaction_type",
    "path": [
      "interaction_type"
    ],
    "label": "Interaction Type",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Use the service's interaction_type (e.g. online, skype, client_phone, business_location)"
  },
  {
    "key": "interaction_details",
    "path": [
      "interaction_details"
    ],
    "label": "Interaction Details",
    "type": "string",
    "required": false,
    "isJson": false,
    "default": "",
    "helpText": "Phone/address per interaction_type; leave blank for online/video"
  },
  {
    "key": "charge_type",
    "path": [
      "charge_type"
    ],
    "label": "Charge Type",
    "type": "string",
    "required": false,
    "isJson": false,
    "default": "no_price",
    "choices": [
      "no_price",
      "fixed",
      "custom"
    ]
  },
  {
    "key": "source_type",
    "path": [
      "source_type"
    ],
    "label": "Source",
    "type": "string",
    "required": false,
    "isJson": false,
    "default": "initiated_by_staff",
    "choices": [
      "initiated_by_staff",
      "initiated_by_client"
    ]
  }
];
const pathFields = [];
// client_matter (D030): matter_uid is resolved from the chosen client (either a
// synthetic Client picker or an existing client_id field) and injected at these
// body paths. CLIENT_FIELD is the synthetic UI-only field (null when reusing a
// native client_id); CLIENT_SOURCE_KEY is the inputData key to resolve from.
const CLIENT_FIELD = null;
const CLIENT_SOURCE_KEY = null;
const MATTER_PATHS = [];
// Body shaping: WRAP_ARRAY wraps the built body as { [WRAP_ARRAY]: [body] };
// BODY_CONST merges constant keys at the top level (e.g. { new_api: true }).
const WRAP_ARRAY = "appointments";
const BODY_CONST = {
  "new_api": true
};

const inputFields = [
  ...pathFields,
  ...(CLIENT_FIELD ? [toInputField(CLIENT_FIELD)] : []),
  ...bodyFields.map(toInputField),
];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "business_id": "j9q05nvfv12w79vl",
  "appointment_id": "3in0a3b32nut67l6",
  "conversation_id": "pto6yng4e908c8g0",
  "title": "Introductory Phone Call",
  "client_id": "54gjvtadfbxiom7y",
  "staff_id": "e6j4i1ofy2pf0dmg",
  "start_time": "2019-10-29T10:00:00.000+02:00",
  "end_time": "2019-10-29T10:30:00.000+02:00",
  "duration": 30,
  "service_uid": "02nbrfqxys1gmoj2",
  "notes": "",
  "interaction_details": "123456",
  "currency": "ILS",
  "payment_id": null,
  "where": "phone",
  "source_data": {
    "id": 215954943,
    "name": "initiated_by_staff",
    "channel": null,
    "campaign": null,
    "website_url": null
  }
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const body = buildBody(bundle.inputData, bodyFields);
  if (CLIENT_SOURCE_KEY && MATTER_PATHS.length) {
    const matterUid = await resolveMatterUid(z, bundle, bundle.inputData[CLIENT_SOURCE_KEY]);
    if (CLIENT_FIELD && CLIENT_FIELD.required && !matterUid) {
      throw new z.errors.Error(
        'Could not find a matter for the selected client. Pick a client that has at least one matter.',
        'MatterNotFound'
      );
    }
    if (matterUid) for (const p of MATTER_PATHS) setByPath(body, p, matterUid);
  }
  let payload = body;
  if (WRAP_ARRAY) payload = { [WRAP_ARRAY]: [body], ...(BODY_CONST || {}) };
  else if (BODY_CONST) payload = { ...body, ...BODY_CONST };
  const response = await z.request({ url, method: METHOD, body: payload });
  return response.data;
};

module.exports = {
  key: "booking",
  noun: "Appointment",
  display: {
    label: "Create Booking",
    description: "Create a appointment in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
