// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField } = require('../utils');

const PATH = "/platform/v1/scheduling/bookings";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "business_id",
    "path": [
      "business_id"
    ],
    "label": "Business Id",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Business uid"
  },
  {
    "key": "campaign",
    "path": [
      "campaign"
    ],
    "label": "Campaign",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source campaign"
  },
  {
    "key": "channel",
    "path": [
      "channel"
    ],
    "label": "Channel",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source channel"
  },
  {
    "key": "client_id",
    "path": [
      "client_id"
    ],
    "label": "Client Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Client uid. If not provided, form_data with client fields (email, first_name) is required."
  },
  {
    "key": "event_instance_id",
    "path": [
      "event_instance_id"
    ],
    "label": "Event Instance Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Event instance uid. Required for event registration (not appointment booking)."
  },
  {
    "key": "form_data__fields",
    "path": [
      "form_data",
      "fields"
    ],
    "label": "Fields",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Array of field objects. Each object must have field_id (from form definition), type (field type like 'email', 'first_name'), and new_data (the value as string). (JSON)"
  },
  {
    "key": "form_data__service_fields",
    "path": [
      "form_data",
      "service_fields"
    ],
    "label": "Service Fields",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Service-specific custom fields (same structure as fields) (JSON)"
  },
  {
    "key": "form_data__meeting_details__meeting_interaction_details",
    "path": [
      "form_data",
      "meeting_details",
      "meeting_interaction_details"
    ],
    "label": "Meeting Interaction Details",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Location or contact details for the meeting"
  },
  {
    "key": "form_data__others__notes",
    "path": [
      "form_data",
      "others",
      "notes"
    ],
    "label": "Notes",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Optional notes for the booking"
  },
  {
    "key": "form_data__policies",
    "path": [
      "form_data",
      "policies"
    ],
    "label": "Policies",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Policy acceptance data (JSON)"
  },
  {
    "key": "matter_uid",
    "path": [
      "matter_uid"
    ],
    "label": "Matter Uid",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Matter uid (conversation context)"
  },
  {
    "key": "portal_id",
    "path": [
      "portal_id"
    ],
    "label": "Portal Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Business uid (same as business_id, for portal context)"
  },
  {
    "key": "service_id",
    "path": [
      "service_id"
    ],
    "label": "Service Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Service uid. Required for appointment booking."
  },
  {
    "key": "source_name",
    "path": [
      "source_name"
    ],
    "label": "Source Name",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source name (e.g., 'client_portal', 'api')"
  },
  {
    "key": "source_url",
    "path": [
      "source_url"
    ],
    "label": "Source Url",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source URL"
  },
  {
    "key": "staff_id",
    "path": [
      "staff_id"
    ],
    "label": "Staff Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Staff uid. Required for appointment booking."
  },
  {
    "key": "start_time",
    "path": [
      "start_time"
    ],
    "label": "Start Time",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "ISO 8601 format. Required for appointment."
  },
  {
    "key": "time_zone",
    "path": [
      "time_zone"
    ],
    "label": "Time Zone",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Default is set to UTC if not provided"
  }
];
const pathFields = [];

const inputFields = [...pathFields, ...bodyFields.map(toInputField)];

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const response = await z.request({
    url,
    method: METHOD,
    body: buildBody(bundle.inputData, bodyFields),
  });
  return response.data;
};

module.exports = {
  key: "booking",
  noun: "Appointment",
  display: {
    label: "Create Booking",
    description: "Create a appointment in inTandem.",
  },
  operation: { inputFields, perform },
};
