// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField, resolveMatterUid, setByPath } = require('../utils');

const PATH = "/platform/v1/scheduling/bookings";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "business_id",
    "path": [
      "business_id"
    ],
    "label": "Business Id",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Business uid"
  },
  {
    "key": "campaign",
    "path": [
      "campaign"
    ],
    "label": "Campaign",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source campaign"
  },
  {
    "key": "channel",
    "path": [
      "channel"
    ],
    "label": "Channel",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source channel"
  },
  {
    "key": "client_id",
    "path": [
      "client_id"
    ],
    "label": "Client Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Client uid. If not provided, form_data with client fields (email, first_name) is required.",
    "dynamic": "list_clients.id.label"
  },
  {
    "key": "event_instance_id",
    "path": [
      "event_instance_id"
    ],
    "label": "Event Instance Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Event instance uid. Required for event registration (not appointment booking)."
  },
  {
    "key": "form_data__fields",
    "path": [
      "form_data",
      "fields"
    ],
    "label": "Fields",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Array of field objects. Each object must have field_id (from form definition), type (field type like 'email', 'first_name'), and new_data (the value as string). (JSON)"
  },
  {
    "key": "form_data__service_fields",
    "path": [
      "form_data",
      "service_fields"
    ],
    "label": "Service Fields",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Service-specific custom fields (same structure as fields) (JSON)"
  },
  {
    "key": "form_data__meeting_details__meeting_interaction_details",
    "path": [
      "form_data",
      "meeting_details",
      "meeting_interaction_details"
    ],
    "label": "Meeting Interaction Details",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Location or contact details for the meeting"
  },
  {
    "key": "form_data__others__notes",
    "path": [
      "form_data",
      "others",
      "notes"
    ],
    "label": "Notes",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Optional notes for the booking"
  },
  {
    "key": "form_data__policies",
    "path": [
      "form_data",
      "policies"
    ],
    "label": "Policies",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Policy acceptance data (JSON)"
  },
  {
    "key": "matter_uid",
    "path": [
      "matter_uid"
    ],
    "label": "Matter Uid",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Matter uid (conversation context)"
  },
  {
    "key": "portal_id",
    "path": [
      "portal_id"
    ],
    "label": "Portal Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Business uid (same as business_id, for portal context)"
  },
  {
    "key": "service_id",
    "path": [
      "service_id"
    ],
    "label": "Service Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Service uid. Required for appointment booking.",
    "dynamic": "list_services.id.label"
  },
  {
    "key": "source_name",
    "path": [
      "source_name"
    ],
    "label": "Source Name",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source name (e.g., 'client_portal', 'api')"
  },
  {
    "key": "source_url",
    "path": [
      "source_url"
    ],
    "label": "Source Url",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "staff_id",
    "path": [
      "staff_id"
    ],
    "label": "Staff Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Staff uid. Required for appointment booking.",
    "dynamic": "list_staff.id.label"
  },
  {
    "key": "start_time",
    "path": [
      "start_time"
    ],
    "label": "Start Time",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "ISO 8601 format. Required for appointment."
  },
  {
    "key": "time_zone",
    "path": [
      "time_zone"
    ],
    "label": "Time Zone",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Default is set to UTC if not provided"
  }
];
const pathFields = [];
// client_matter (D030): matter_uid is resolved from the chosen client (either a
// synthetic Client picker or an existing client_id field) and injected at these
// body paths. CLIENT_FIELD is the synthetic UI-only field (null when reusing a
// native client_id); CLIENT_SOURCE_KEY is the inputData key to resolve from.
const CLIENT_FIELD = null;
const CLIENT_SOURCE_KEY = null;
const MATTER_PATHS = [];

const inputFields = [
  ...pathFields,
  ...(CLIENT_FIELD ? [toInputField(CLIENT_FIELD)] : []),
  ...bodyFields.map(toInputField),
];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "business_id": "j9q05nvfv12w79vl",
  "appointment_id": "3in0a3b32nut67l6",
  "conversation_id": "pto6yng4e908c8g0",
  "title": "Introductory Phone Call",
  "client_id": "54gjvtadfbxiom7y",
  "staff_id": "e6j4i1ofy2pf0dmg",
  "start_time": "2019-10-29T10:00:00.000+02:00",
  "end_time": "2019-10-29T10:30:00.000+02:00",
  "duration": 30,
  "service_uid": "02nbrfqxys1gmoj2",
  "notes": "",
  "interaction_details": "123456",
  "currency": "ILS",
  "payment_id": null,
  "where": "phone",
  "source_data": {
    "id": 215954943,
    "name": "initiated_by_staff",
    "channel": null,
    "campaign": null,
    "website_url": null
  }
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const body = buildBody(bundle.inputData, bodyFields);
  if (CLIENT_SOURCE_KEY && MATTER_PATHS.length) {
    const matterUid = await resolveMatterUid(z, bundle, bundle.inputData[CLIENT_SOURCE_KEY]);
    if (CLIENT_FIELD && CLIENT_FIELD.required && !matterUid) {
      throw new z.errors.Error(
        'Could not find a matter for the selected client. Pick a client that has at least one matter.',
        'MatterNotFound'
      );
    }
    if (matterUid) for (const p of MATTER_PATHS) setByPath(body, p, matterUid);
  }
  const response = await z.request({ url, method: METHOD, body });
  return response.data;
};

module.exports = {
  key: "booking",
  noun: "Appointment",
  display: {
    label: "Create Booking",
    description: "Create a appointment in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
