// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField } = require('../utils');

const PATH = "/platform/v1/clients";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "address",
    "path": [
      "address"
    ],
    "label": "Address",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "custom_field1",
    "path": [
      "custom_field1"
    ],
    "label": "Custom Field1",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "custom_field2",
    "path": [
      "custom_field2"
    ],
    "label": "Custom Field2",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "custom_field3",
    "path": [
      "custom_field3"
    ],
    "label": "Custom Field3",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "email",
    "path": [
      "email"
    ],
    "label": "Email",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Email Address. Must be a valid email format (e.g., user@example.com)"
  },
  {
    "key": "first_name",
    "path": [
      "first_name"
    ],
    "label": "First Name",
    "type": "string",
    "required": true,
    "isJson": false
  },
  {
    "key": "last_name",
    "path": [
      "last_name"
    ],
    "label": "Last Name",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "opt_in",
    "path": [
      "opt_in"
    ],
    "label": "Opt In",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Marketing email opt-in status. Accepts boolean values (`true` / `false`) or string values (`\"1\"` / `\"0\"`). When set to `true` (or `\"1\"`), the client is opted in to receive marketing emails; when set to `false` (or `\"0\"`), the client is opted out. This is distinct from `opt_in_transactional_sms`, which controls transactional SMS consent."
  },
  {
    "key": "opt_in_transactional_sms",
    "path": [
      "opt_in_transactional_sms"
    ],
    "label": "Opt In Transactional Sms",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Whether the client opts in to receive transactional SMS messages."
  },
  {
    "key": "phone",
    "path": [
      "phone"
    ],
    "label": "Phone",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Phone Number"
  },
  {
    "key": "source_campaign",
    "path": [
      "source_campaign"
    ],
    "label": "Source Campaign",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "source_channel",
    "path": [
      "source_channel"
    ],
    "label": "Source Channel",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "source_name",
    "path": [
      "source_name"
    ],
    "label": "Source Name",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "source_url",
    "path": [
      "source_url"
    ],
    "label": "Source Url",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "staff_id",
    "path": [
      "staff_id"
    ],
    "label": "Staff Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Staff ID. Reference to the staff member (see staff entity).",
    "dynamic": "list_staff.id.label"
  },
  {
    "key": "status",
    "path": [
      "status"
    ],
    "label": "Status",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Use a client status to categorize clients according to their relationship with your business. Valid values: lead, customer, loyal, inactive",
    "choices": [
      "lead",
      "customer",
      "loyal",
      "inactive"
    ]
  },
  {
    "key": "tags",
    "path": [
      "tags"
    ],
    "label": "Tags",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The tag system is based on customized labels that you create, so you can sort your data using personalized words, phrases or themes that are meaningful to you and your business"
  }
];
const pathFields = [];

const inputFields = [...pathFields, ...bodyFields.map(toInputField)];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "business_id": "s5ek7tfgp068i2st",
  "client_id": "k7zcc3nhb1aijzms",
  "first_name": "New",
  "last_name": "Client",
  "phone": "05544778899",
  "email": "user@email.com",
  "image": "http://www.meet2know.com/assets/img-avatar.gif",
  "address": {
    "main": "New York"
  },
  "custom_fields": {
    "Birthday": "1985-10-15"
  },
  "visible": true,
  "opt_in": null,
  "created_at": "2019-10-29T07:29:30Z",
  "updated_at": "2023-04-24T18:28:10.000+03:00",
  "spam": false
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const response = await z.request({
    url,
    method: METHOD,
    body: buildBody(bundle.inputData, bodyFields),
  });
  return response.data;
};

module.exports = {
  key: "client",
  noun: "Client",
  display: {
    label: "Create Client",
    description: "Create a client in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
