// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField } = require('../utils');

const PATH = "/v3/clients/client_notes";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "matter_uid",
    "path": [
      "matter_uid"
    ],
    "label": "Matter Uid",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Unique identifier of the client matter this note belongs to",
    "dynamic": "list_matters.id.label"
  },
  {
    "key": "content",
    "path": [
      "content"
    ],
    "label": "Content",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The HTML or text content of the note. May contain HTML markup for rich text formatting (e.g., \"<div>some note here</div>\"). Can be empty. At least one of title or content must be provided."
  },
  {
    "key": "title",
    "path": [
      "title"
    ],
    "label": "Title",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Title for the note. Provides a brief heading or subject line for the note content. At least one of title or content must be provided."
  },
  {
    "key": "entity_uid",
    "path": [
      "entity_uid"
    ],
    "label": "Entity Uid",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Unique identifier of the entity this note is associated with (e.g., document, payment, meeting). Optional - omit if the note is not linked to any specific entity."
  },
  {
    "key": "entity_type",
    "path": [
      "entity_type"
    ],
    "label": "Entity Type",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Type of entity this note is associated with. Required if entity_uid is provided. Possible values: document (note linked to a document), payment (note linked to a payment), meeting (note linked to a meeting).",
    "choices": [
      "document",
      "payment",
      "meeting"
    ]
  }
];
const pathFields = [];

const inputFields = [...pathFields, ...bodyFields.map(toInputField)];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "uid": "sample-client_note-uid"
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const response = await z.request({
    url,
    method: METHOD,
    body: buildBody(bundle.inputData, bodyFields),
  });
  return response.data;
};

module.exports = {
  key: "client_note",
  noun: "Client Note",
  display: {
    label: "Create Client Note",
    description: "Create a client note in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
