// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField, resolveMatterUid, setByPath } = require('../utils');

const PATH = "/v3/clients/client_notes";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "content",
    "path": [
      "content"
    ],
    "label": "Content",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The HTML or text content of the note. May contain HTML markup for rich text formatting (e.g., \"<div>some note here</div>\"). Can be empty. At least one of title or content must be provided."
  },
  {
    "key": "title",
    "path": [
      "title"
    ],
    "label": "Title",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Title for the note. Provides a brief heading or subject line for the note content. At least one of title or content must be provided."
  },
  {
    "key": "entity_uid",
    "path": [
      "entity_uid"
    ],
    "label": "Entity Uid",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Unique identifier of the entity this note is associated with (e.g., document, payment, meeting). Optional - omit if the note is not linked to any specific entity."
  },
  {
    "key": "entity_type",
    "path": [
      "entity_type"
    ],
    "label": "Entity Type",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Type of entity this note is associated with. Required if entity_uid is provided. Possible values: document (note linked to a document), payment (note linked to a payment), meeting (note linked to a meeting).",
    "choices": [
      "document",
      "payment",
      "meeting"
    ]
  }
];
const pathFields = [];
// client_matter (D030): matter_uid is resolved from the chosen client (either a
// synthetic Client picker or an existing client_id field) and injected at these
// body paths. CLIENT_FIELD is the synthetic UI-only field (null when reusing a
// native client_id); CLIENT_SOURCE_KEY is the inputData key to resolve from.
const CLIENT_FIELD = {
  "key": "client_id",
  "label": "Client",
  "type": "string",
  "required": true,
  "dynamic": "list_clients.id.label",
  "helpText": "The client to attach this to — their matter is resolved automatically."
};
const CLIENT_SOURCE_KEY = "client_id";
const MATTER_PATHS = [
  [
    "matter_uid"
  ]
];
// Body shaping: WRAP_ARRAY wraps the built body as { [WRAP_ARRAY]: [body] };
// BODY_CONST merges constant keys at the top level (e.g. { new_api: true }).
const WRAP_ARRAY = null;
const BODY_CONST = null;

const inputFields = [
  ...pathFields,
  ...(CLIENT_FIELD ? [toInputField(CLIENT_FIELD)] : []),
  ...bodyFields.map(toInputField),
];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "uid": "sample-client_note-uid"
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const body = buildBody(bundle.inputData, bodyFields);
  if (CLIENT_SOURCE_KEY && MATTER_PATHS.length) {
    const matterUid = await resolveMatterUid(z, bundle, bundle.inputData[CLIENT_SOURCE_KEY]);
    if (CLIENT_FIELD && CLIENT_FIELD.required && !matterUid) {
      throw new z.errors.Error(
        'Could not find a matter for the selected client. Pick a client that has at least one matter.',
        'MatterNotFound'
      );
    }
    if (matterUid) for (const p of MATTER_PATHS) setByPath(body, p, matterUid);
  }
  let payload = body;
  if (WRAP_ARRAY) payload = { [WRAP_ARRAY]: [body], ...(BODY_CONST || {}) };
  else if (BODY_CONST) payload = { ...body, ...BODY_CONST };
  const response = await z.request({ url, method: METHOD, body: payload });
  return response.data;
};

module.exports = {
  key: "client_note",
  noun: "Client Note",
  display: {
    label: "Create Client Note",
    description: "Create a client note in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
