// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField } = require('../utils');

const PATH = "/business/payments/v1/estimates";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "estimate__billing_address",
    "path": [
      "estimate",
      "billing_address"
    ],
    "label": "Billing Address",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Business billing address"
  },
  {
    "key": "estimate__business_name",
    "path": [
      "estimate",
      "business_name"
    ],
    "label": "Business Name",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The business name. Default value: The business name"
  },
  {
    "key": "estimate__currency",
    "path": [
      "estimate",
      "currency"
    ],
    "label": "Currency",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Three-letter ISO currency code"
  },
  {
    "key": "estimate__display_items_total",
    "path": [
      "estimate",
      "display_items_total"
    ],
    "label": "Display Items Total",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Indicates wheter items total amounts should be displayed in the estimate. Default is true"
  },
  {
    "key": "estimate__display_sections_total",
    "path": [
      "estimate",
      "display_sections_total"
    ],
    "label": "Display Sections Total",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Indicates wheter sections total amounts should be displayed in the estimate. Default is true"
  },
  {
    "key": "estimate__due_date",
    "path": [
      "estimate",
      "due_date"
    ],
    "label": "Due Date",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "The date when the estimate is due, in YYYY-MM-DD format (based on the timezone of the business), must be equal or greater than the estimate issue date"
  },
  {
    "key": "estimate__estimate_label",
    "path": [
      "estimate",
      "estimate_label"
    ],
    "label": "Estimate Label",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The invoice label. Default value: ESTIMATE (in the business locale)"
  },
  {
    "key": "estimate__estimate_number",
    "path": [
      "estimate",
      "estimate_number"
    ],
    "label": "Estimate Number",
    "type": "number",
    "required": false,
    "isJson": false,
    "helpText": "A unique estimate number. Default value: last estimate number increment by 1"
  },
  {
    "key": "estimate__is_signature_required",
    "path": [
      "estimate",
      "is_signature_required"
    ],
    "label": "Is Signature Required",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Indicates whether signature is required for the specific estimate"
  },
  {
    "key": "estimate__issue_date",
    "path": [
      "estimate",
      "issue_date"
    ],
    "label": "Issue Date",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Estimate date, in YYYY-MM-DD format (based on the timezone of the business)"
  },
  {
    "key": "estimate__items",
    "path": [
      "estimate",
      "items"
    ],
    "label": "Items",
    "type": "text",
    "required": true,
    "isJson": true,
    "helpText": "An array of estimate item information. At least one item is required (unless sections provided). (JSON)"
  },
  {
    "key": "estimate__matter_uid",
    "path": [
      "estimate",
      "matter_uid"
    ],
    "label": "Matter Uid",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Matter UID"
  },
  {
    "key": "estimate__note",
    "path": [
      "estimate",
      "note"
    ],
    "label": "Note",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "A note for the invoice recipient"
  },
  {
    "key": "estimate__notify_recipient",
    "path": [
      "estimate",
      "notify_recipient"
    ],
    "label": "Notify Recipient",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Indicates whether to send the estimate to the recipient. This can be set only on ISSUED estimate. Default value: true"
  },
  {
    "key": "estimate__purchase_order",
    "path": [
      "estimate",
      "purchase_order"
    ],
    "label": "Purchase Order",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Purchase Order"
  },
  {
    "key": "estimate__sections",
    "path": [
      "estimate",
      "sections"
    ],
    "label": "Sections",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "An array of estimate sections information. requires if not general items provided. (JSON)"
  },
  {
    "key": "estimate__source_campaign",
    "path": [
      "estimate",
      "source_campaign"
    ],
    "label": "Source Campaign",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source Campaign"
  },
  {
    "key": "estimate__source_channel",
    "path": [
      "estimate",
      "source_channel"
    ],
    "label": "Source Channel",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source Channel"
  },
  {
    "key": "estimate__source_name",
    "path": [
      "estimate",
      "source_name"
    ],
    "label": "Source Name",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source Name"
  },
  {
    "key": "estimate__source_url",
    "path": [
      "estimate",
      "source_url"
    ],
    "label": "Source Url",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Source Url"
  },
  {
    "key": "estimate__status",
    "path": [
      "estimate",
      "status"
    ],
    "label": "Status",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The status of the estimate. The possible values are: DRAFT / ISSUED. Default value: ISSUED"
  },
  {
    "key": "estimate__terms_and_conditions",
    "path": [
      "estimate",
      "terms_and_conditions"
    ],
    "label": "Terms And Conditions",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The terms and conditions of the estimate"
  }
];
const pathFields = [];

const inputFields = [...pathFields, ...bodyFields.map(toInputField)];

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const response = await z.request({
    url,
    method: METHOD,
    body: buildBody(bundle.inputData, bodyFields),
  });
  return response.data;
};

module.exports = {
  key: "estimate",
  noun: "Estimate",
  display: {
    label: "Create Estimate",
    description: "Create a estimate in vcita.",
  },
  operation: { inputFields, perform },
};
