// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField } = require('../utils');

const PATH = "/business/payments/v1/invoices";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "invoice__additional_recipients",
    "path": [
      "invoice",
      "additional_recipients"
    ],
    "label": "Additional Recipients",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "An array of email addresses of additional recipients to notify (JSON)"
  },
  {
    "key": "invoice__allow_online_payment",
    "path": [
      "invoice",
      "allow_online_payment"
    ],
    "label": "Allow Online Payment",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Indicates whether an online payment is allowed for this invoice. This can be set for business with online payment enabled and when connected to a payment gateway. Default value: true when connected to a payment gateway and online payment is enabled for the business."
  },
  {
    "key": "invoice__allow_partial_payment",
    "path": [
      "invoice",
      "allow_partial_payment"
    ],
    "label": "Allow Partial Payment",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Indicates whether a partial payment is allowed for this invoice. This can be set when online payment is allowed for the invoice. Default value: true when online payment allowed for the invoice and partial payment is enabled for the business."
  },
  {
    "key": "invoice__billing_address",
    "path": [
      "invoice",
      "billing_address"
    ],
    "label": "Billing Address",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Business billing address"
  },
  {
    "key": "invoice__business_name",
    "path": [
      "invoice",
      "business_name"
    ],
    "label": "Business Name",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The business name. Default value: The business name"
  },
  {
    "key": "invoice__currency",
    "path": [
      "invoice",
      "currency"
    ],
    "label": "Currency",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Three-letter ISO currency code"
  },
  {
    "key": "invoice__display_items_total",
    "path": [
      "invoice",
      "display_items_total"
    ],
    "label": "Display Items Total",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Indicates wheter items total amounts should be displayed in the invoice. Default is true"
  },
  {
    "key": "invoice__display_sections_total",
    "path": [
      "invoice",
      "display_sections_total"
    ],
    "label": "Display Sections Total",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Indicates wheter sections total amounts should be displayed in the invoice. Default is true"
  },
  {
    "key": "invoice__due_date",
    "path": [
      "invoice",
      "due_date"
    ],
    "label": "Due Date",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "The date when the invoice payment is due, in YYYY-MM-DD format (based on the timezone of the business), must be equal or greater than the invoice issue date"
  },
  {
    "key": "invoice__from_estimate_uid",
    "path": [
      "invoice",
      "from_estimate_uid"
    ],
    "label": "From Estimate Uid",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The UID of the estimate from which the invoice was created.",
    "dynamic": "list_estimates.id.label"
  },
  {
    "key": "invoice__invoice_label",
    "path": [
      "invoice",
      "invoice_label"
    ],
    "label": "Invoice Label",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The invoice label. Default value: INVOICE (in the business locale)"
  },
  {
    "key": "invoice__invoice_number",
    "path": [
      "invoice",
      "invoice_number"
    ],
    "label": "Invoice Number",
    "type": "number",
    "required": false,
    "isJson": false,
    "helpText": "A unique invoice number. Default value: last invoice number increment by 1"
  },
  {
    "key": "invoice__issue_date",
    "path": [
      "invoice",
      "issue_date"
    ],
    "label": "Issue Date",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Invoice date, in YYYY-MM-DD format (based on the timezone of the business)"
  },
  {
    "key": "invoice__items",
    "path": [
      "invoice",
      "items"
    ],
    "label": "Items",
    "type": "text",
    "required": true,
    "isJson": true,
    "helpText": "An array of invoice item information. At least one item is required (unless sections provided). (JSON)"
  },
  {
    "key": "invoice__matter_uid",
    "path": [
      "invoice",
      "matter_uid"
    ],
    "label": "Matter Uid",
    "type": "string",
    "required": true,
    "isJson": false
  },
  {
    "key": "invoice__note",
    "path": [
      "invoice",
      "note"
    ],
    "label": "Note",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "A note for the invoice recipient"
  },
  {
    "key": "invoice__notify_recipient",
    "path": [
      "invoice",
      "notify_recipient"
    ],
    "label": "Notify Recipient",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Indicates whether to send the invoice to the recipient. This can be set only on ISSUED invoice. Default value: true"
  },
  {
    "key": "invoice__purchase_order",
    "path": [
      "invoice",
      "purchase_order"
    ],
    "label": "Purchase Order",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "invoice__sections",
    "path": [
      "invoice",
      "sections"
    ],
    "label": "Sections",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "An array of invoice sections information. requires if not general items provided. (JSON)"
  },
  {
    "key": "invoice__source_campaign",
    "path": [
      "invoice",
      "source_campaign"
    ],
    "label": "Source Campaign",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "invoice__source_channel",
    "path": [
      "invoice",
      "source_channel"
    ],
    "label": "Source Channel",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "invoice__source_name",
    "path": [
      "invoice",
      "source_name"
    ],
    "label": "Source Name",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "invoice__source_url",
    "path": [
      "invoice",
      "source_url"
    ],
    "label": "Source Url",
    "type": "string",
    "required": false,
    "isJson": false
  },
  {
    "key": "invoice__status",
    "path": [
      "invoice",
      "status"
    ],
    "label": "Status",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The status of the invoice. The possible values are: DRAFT / ISSUED. Default value: ISSUED"
  },
  {
    "key": "invoice__terms_and_conditions",
    "path": [
      "invoice",
      "terms_and_conditions"
    ],
    "label": "Terms And Conditions",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The terms and conditions of the invoice"
  }
];
const pathFields = [];

const inputFields = [...pathFields, ...bodyFields.map(toInputField)];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "business_id": "s5ek7tfgp068i2st",
  "staff_id": "e6j4i1ofy2pf0dmg",
  "conversation_id": "pto6yng4e908c8g0",
  "invoice_id": "ujjq3chk5jv91y0q",
  "state": "issued",
  "title": "#0000001",
  "issued_at": "2019-10-29",
  "due_date": "2019-11-28",
  "invoice_number": 1,
  "address": "Tel Aviv",
  "note": null,
  "amount": "35.84",
  "currency": "ILS",
  "charge_at": null,
  "client_id": "54gjvtadfbxiom7y",
  "created_at": "2019-10-29T09:33:43.000+02:00",
  "items": [
    {
      "title": "Demo Class / Event",
      "amount": "35.84",
      "tax": "3.84"
    }
  ]
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const response = await z.request({
    url,
    method: METHOD,
    body: buildBody(bundle.inputData, bodyFields),
  });
  return response.data;
};

module.exports = {
  key: "invoice",
  noun: "Invoice",
  display: {
    label: "Create Invoice",
    description: "Create a invoice in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
