// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField, resolveMatterUid, setByPath } = require('../utils');

const PATH = "/platform/v1/leadgen";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "address",
    "path": [
      "address"
    ],
    "label": "Address",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Lead's address"
  },
  {
    "key": "business_id",
    "path": [
      "business_id"
    ],
    "label": "Business Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "A unique identifier of the business. Can be the Business UID or nickname\\external ID."
  },
  {
    "key": "email",
    "path": [
      "email"
    ],
    "label": "Email",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Lead email address. Unique per business."
  },
  {
    "key": "first_name",
    "path": [
      "first_name"
    ],
    "label": "First Name",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Lead first name. Mandatory for a new lead."
  },
  {
    "key": "identifier_type",
    "path": [
      "identifier_type"
    ],
    "label": "Identifier Type",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Defines which unique identifier will be used to search for an existing lead or create a new one. Possible values: \"email\" or \"unique_id\""
  },
  {
    "key": "last_name",
    "path": [
      "last_name"
    ],
    "label": "Last Name",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Lead last name."
  },
  {
    "key": "message_data",
    "path": [
      "message_data"
    ],
    "label": "Message Data",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Key and value that will appear in message (JSON)"
  },
  {
    "key": "notifications",
    "path": [
      "notifications"
    ],
    "label": "Notifications",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "A list of notifications to send after processing of the lead. Possible values: \"auto-reply\" (thank you email to the end user), \"email\" (notify the business owner) or \"sms\" (text notification to the business owner). None if empty."
  },
  {
    "key": "opt_in",
    "path": [
      "opt_in"
    ],
    "label": "Opt In",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Send \"true\" if lead opted in for promotions. Make sure the \"opt-in\" client card field is added to the client card under Settings>Client card."
  },
  {
    "key": "opt_in_transactional_sms",
    "path": [
      "opt_in_transactional_sms"
    ],
    "label": "Opt In Transactional Sms",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Whether the client opts in to receive transactional SMS messages."
  },
  {
    "key": "phone",
    "path": [
      "phone"
    ],
    "label": "Phone",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Lead phone number."
  },
  {
    "key": "request_data",
    "path": [
      "request_data"
    ],
    "label": "Request Data",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Key and value properties that will update new lead and appear in message (JSON)"
  },
  {
    "key": "request_title",
    "path": [
      "request_title"
    ],
    "label": "Request Title",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Request title. Will also be the created conversation title."
  },
  {
    "key": "source",
    "path": [
      "source"
    ],
    "label": "Source",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Will be displayed to the business owner as the lead source"
  },
  {
    "key": "source_url",
    "path": [
      "source_url"
    ],
    "label": "Source Url",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The URL of the page where the lead was created."
  },
  {
    "key": "status",
    "path": [
      "status"
    ],
    "label": "Status",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Use a client status to categorize clients according to their relationship with your business, default is Lead."
  },
  {
    "key": "system_message",
    "path": [
      "system_message"
    ],
    "label": "System Message",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "A message displayed to the business owner to introduce the lead. May contain links."
  },
  {
    "key": "tags",
    "path": [
      "tags"
    ],
    "label": "Tags",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Customized labels that enbale you to sort your data using personalized words, phrases or themes that are meaningful to you and your business"
  },
  {
    "key": "unique_id",
    "path": [
      "unique_id"
    ],
    "label": "Unique Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Lead unique id. Unique per business."
  }
];
const pathFields = [];
// client_matter (D030): matter_uid is resolved from the chosen client (either a
// synthetic Client picker or an existing client_id field) and injected at these
// body paths. CLIENT_FIELD is the synthetic UI-only field (null when reusing a
// native client_id); CLIENT_SOURCE_KEY is the inputData key to resolve from.
const CLIENT_FIELD = null;
const CLIENT_SOURCE_KEY = null;
const MATTER_PATHS = [];

const inputFields = [
  ...pathFields,
  ...(CLIENT_FIELD ? [toInputField(CLIENT_FIELD)] : []),
  ...bodyFields.map(toInputField),
];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "uid": "sample-lead-uid"
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const body = buildBody(bundle.inputData, bodyFields);
  if (CLIENT_SOURCE_KEY && MATTER_PATHS.length) {
    const matterUid = await resolveMatterUid(z, bundle, bundle.inputData[CLIENT_SOURCE_KEY]);
    if (CLIENT_FIELD && CLIENT_FIELD.required && !matterUid) {
      throw new z.errors.Error(
        'Could not find a matter for the selected client. Pick a client that has at least one matter.',
        'MatterNotFound'
      );
    }
    if (matterUid) for (const p of MATTER_PATHS) setByPath(body, p, matterUid);
  }
  const response = await z.request({ url, method: METHOD, body });
  return response.data;
};

module.exports = {
  key: "lead",
  noun: "Lead",
  display: {
    label: "Create Lead",
    description: "Create a lead in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
