// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField, resolveMatterUid, setByPath } = require('../utils');

const PATH = "/platform/v1/messages";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "message__channels",
    "path": [
      "message",
      "channels"
    ],
    "label": "Channels",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Comma-separated list of delivery channels (e.g., \"sms\", \"email\"). When omitted, the message is sent to all available channels."
  },
  {
    "key": "message__client_id",
    "path": [
      "message",
      "client_id"
    ],
    "label": "Client Id",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "The UID of the recipient client. Required to identify the target contact and resolve the conversation.",
    "dynamic": "list_clients.id.label"
  },
  {
    "key": "message__conversation_title",
    "path": [
      "message",
      "conversation_title"
    ],
    "label": "Conversation Title",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Title for the conversation. Optional; used when creating a new conversation."
  },
  {
    "key": "message__conversation_uid",
    "path": [
      "message",
      "conversation_uid"
    ],
    "label": "Conversation Uid",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "UID of an existing conversation to add the message to. If omitted, the system creates or uses the client's default conversation."
  },
  {
    "key": "message__direction",
    "path": [
      "message",
      "direction"
    ],
    "label": "Direction",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "The direction of the message. Required. Valid values: \"client_to_business\", \"business_to_client\".",
    "choices": [
      "client_to_business",
      "business_to_client"
    ]
  },
  {
    "key": "message__staff_id",
    "path": [
      "message",
      "staff_id"
    ],
    "label": "Staff Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "UID of the staff member sending the message. Optional — if omitted, the staff is auto-assigned based on business assignment rules.",
    "dynamic": "list_staff.id.label"
  },
  {
    "key": "message__text",
    "path": [
      "message",
      "text"
    ],
    "label": "Text",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "The text content of the message. Required. Plain text only — do not include HTML tags."
  }
];
const pathFields = [];
// client_matter (D030): matter_uid is resolved from the chosen client (either a
// synthetic Client picker or an existing client_id field) and injected at these
// body paths. CLIENT_FIELD is the synthetic UI-only field (null when reusing a
// native client_id); CLIENT_SOURCE_KEY is the inputData key to resolve from.
const CLIENT_FIELD = null;
const CLIENT_SOURCE_KEY = null;
const MATTER_PATHS = [];
// CLIENT_MATTER_ARRAY_PATH: when set, the resolved matter is injected here as a
// one-element array (e.g. ['matters','uids'] -> body.matters.uids = [matterUid]).
const CLIENT_MATTER_ARRAY_PATH = null;
// QUERY: constant query params sent with the request (e.g. { new_api: true }).
const QUERY = null;
// Body shaping: WRAP_ARRAY wraps the built body as { [WRAP_ARRAY]: [body] };
// BODY_CONST merges constant keys at the top level (e.g. { new_api: true }).
const WRAP_ARRAY = null;
const BODY_CONST = null;

const inputFields = [
  ...pathFields,
  ...(CLIENT_FIELD ? [toInputField(CLIENT_FIELD)] : []),
  ...bodyFields.map(toInputField),
];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "business_id": "s5ek7tfgp068i2st",
  "staff_id": "e6j4i1ofy2pf0dmg",
  "conversation_id": "pto6yng4e908c8g0",
  "message_id": "fjo0q77g2a4hmotc",
  "message": "Thank you for your message",
  "client_id": "54gjvtadfbxiom7y",
  "created_at": "2019-10-29T09:36:59.105+02:00"
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const body = buildBody(bundle.inputData, bodyFields);
  if (CLIENT_SOURCE_KEY && (MATTER_PATHS.length || CLIENT_MATTER_ARRAY_PATH)) {
    const matterUid = await resolveMatterUid(z, bundle, bundle.inputData[CLIENT_SOURCE_KEY]);
    if (CLIENT_FIELD && CLIENT_FIELD.required && !matterUid) {
      throw new z.errors.Error(
        'Could not find a matter for the selected client. Pick a client that has at least one matter.',
        'MatterNotFound'
      );
    }
    if (matterUid) {
      for (const p of MATTER_PATHS) setByPath(body, p, matterUid);
      if (CLIENT_MATTER_ARRAY_PATH) setByPath(body, CLIENT_MATTER_ARRAY_PATH, [matterUid]);
    }
  }
  let payload = body;
  if (WRAP_ARRAY) payload = { [WRAP_ARRAY]: [body], ...(BODY_CONST || {}) };
  else if (BODY_CONST) payload = { ...body, ...BODY_CONST };
  const request = { url, method: METHOD, body: payload };
  if (QUERY) request.params = QUERY;
  const response = await z.request(request);
  return response.data;
};

module.exports = {
  key: "message",
  noun: "Message",
  display: {
    label: "Send Message",
    description: "Create a message in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
