// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField, resolveMatterUid, setByPath } = require('../utils');

const PATH = "/platform/v1/payments";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "amount",
    "path": [
      "amount"
    ],
    "label": "Amount",
    "type": "number",
    "required": true,
    "isJson": false
  },
  {
    "key": "client_id",
    "path": [
      "client_id"
    ],
    "label": "Client Id",
    "type": "string",
    "required": true,
    "isJson": false,
    "dynamic": "list_clients.id.label"
  },
  {
    "key": "currency",
    "path": [
      "currency"
    ],
    "label": "Currency",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "USD, ILS etc."
  },
  {
    "key": "fees",
    "path": [
      "fees"
    ],
    "label": "Fees",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Array of fees (Max 1 fee) (JSON)"
  },
  {
    "key": "mark_as_online",
    "path": [
      "mark_as_online"
    ],
    "label": "Mark As Online",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Enable online refund. Default is disabled"
  },
  {
    "key": "other_payment_method",
    "path": [
      "other_payment_method"
    ],
    "label": "Other Payment Method",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Max 24 chars"
  },
  {
    "key": "paid_at",
    "path": [
      "paid_at"
    ],
    "label": "Paid At",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "default is now"
  },
  {
    "key": "pay_key",
    "path": [
      "pay_key"
    ],
    "label": "Pay Key",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Max 64 chars"
  },
  {
    "key": "payment_method",
    "path": [
      "payment_method"
    ],
    "label": "Payment Method",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Payment method. IMPORTANT: When state is 'pending', the only allowed value is 'Bank Transfer'. For completed (paid) payments (when state is omitted), any value is accepted.",
    "choices": [
      "PayPal",
      "Other",
      "Cash",
      "Credit Card",
      "Bank Transfer",
      "Cheque"
    ]
  },
  {
    "key": "payment_subject_id",
    "path": [
      "payment_subject_id"
    ],
    "label": "Payment Subject Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The ID of the entity for which the payment has been made"
  },
  {
    "key": "payment_subject_type",
    "path": [
      "payment_subject_type"
    ],
    "label": "Payment Subject Type",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The type of entity for which the payment has been made. Available types: 'Meeting', 'EventAttendance', 'Invoice', 'ClientBookingPackage', 'ProductOrder'."
  },
  {
    "key": "reference",
    "path": [
      "reference"
    ],
    "label": "Reference",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Max 24 chars"
  },
  {
    "key": "send_receipt",
    "path": [
      "send_receipt"
    ],
    "label": "Send Receipt",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "true, false. default true"
  },
  {
    "key": "staff_id",
    "path": [
      "staff_id"
    ],
    "label": "Staff Id",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Default is set to the staff that performed the API call. Business owner is allowed to send staff_id",
    "dynamic": "list_staff.id.label"
  },
  {
    "key": "state",
    "path": [
      "state"
    ],
    "label": "State",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Optional. When provided, the ONLY accepted value is 'pending' (creates a pending/unpaid payment that requires Bank Transfer as payment_method). If this field is omitted entirely, the payment is created as completed/paid by default. Do NOT pass 'paid' — it will be rejected.",
    "choices": [
      "pending"
    ]
  },
  {
    "key": "tips",
    "path": [
      "tips"
    ],
    "label": "Tips",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Array of tips (Max 1 tip) (JSON)"
  },
  {
    "key": "title",
    "path": [
      "title"
    ],
    "label": "Title",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "paid for service or product"
  }
];
const pathFields = [];
// client_matter (D030): Client picker replaces matter_uid; matter is resolved
// from the chosen client and injected at these body paths.
const CLIENT_FIELD = null;
const MATTER_PATHS = [];

const inputFields = [
  ...pathFields,
  ...(CLIENT_FIELD ? [toInputField(CLIENT_FIELD)] : []),
  ...bodyFields.map(toInputField),
];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "payment_id": "i80jmue5khmm89mt",
  "business_id": "s36f9j76o95dclwn",
  "conversation_id": "9og26xm7z6vi9hsj",
  "state": "paid",
  "title": "INVOICE #0000011",
  "note": null,
  "amount": 333,
  "currency": "USD",
  "charge_at": "2022-02-06T12:01:35.000Z",
  "refunded_at": null,
  "payment_method": "Bank Transfer",
  "other_payment_method": null,
  "reference": null,
  "offline": true,
  "pay_key": null,
  "payment_request_id": "swv4y4ecobe9s204",
  "payment_requests": [
    {
      "type": "Invoice",
      "id": "zup98lxfmm1aagtk"
    }
  ],
  "client_id": "pnm372tuy83p24f0",
  "created_at": "2022-02-06T12:01:51.000Z"
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const body = buildBody(bundle.inputData, bodyFields);
  if (CLIENT_FIELD && MATTER_PATHS.length) {
    const matterUid = await resolveMatterUid(z, bundle, bundle.inputData[CLIENT_FIELD.key]);
    if (CLIENT_FIELD.required && !matterUid) {
      throw new z.errors.Error(
        'Could not find a matter for the selected client. Pick a client that has at least one matter.',
        'MatterNotFound'
      );
    }
    if (matterUid) for (const p of MATTER_PATHS) setByPath(body, p, matterUid);
  }
  const response = await z.request({ url, method: METHOD, body });
  return response.data;
};

module.exports = {
  key: "payment",
  noun: "Payment",
  display: {
    label: "Create Payment",
    description: "Create a payment in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
