// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField } = require('../utils');

const PATH = "/business/payments/v1/products";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "product__cost",
    "path": [
      "product",
      "cost"
    ],
    "label": "Cost",
    "type": "number",
    "required": false,
    "isJson": false,
    "helpText": "Product cost"
  },
  {
    "key": "product__currency",
    "path": [
      "product",
      "currency"
    ],
    "label": "Currency",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Product currency"
  },
  {
    "key": "product__description",
    "path": [
      "product",
      "description"
    ],
    "label": "Description",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Product description"
  },
  {
    "key": "product__display",
    "path": [
      "product",
      "display"
    ],
    "label": "Display",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Display on products list. Default: true"
  },
  {
    "key": "product__image_url",
    "path": [
      "product",
      "image_url"
    ],
    "label": "Image Url",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Product image URL"
  },
  {
    "key": "product__name",
    "path": [
      "product",
      "name"
    ],
    "label": "Name",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Product name"
  },
  {
    "key": "product__price",
    "path": [
      "product",
      "price"
    ],
    "label": "Price",
    "type": "number",
    "required": true,
    "isJson": false,
    "helpText": "Product price"
  },
  {
    "key": "product__sku",
    "path": [
      "product",
      "sku"
    ],
    "label": "Sku",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Product SKU - must be unique per business"
  },
  {
    "key": "product__tax_ids",
    "path": [
      "product",
      "tax_ids"
    ],
    "label": "Tax Ids",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Product Tax IDs (JSON)"
  }
];
const pathFields = [];

const inputFields = [...pathFields, ...bodyFields.map(toInputField)];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "uid": "sample-product-uid"
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const response = await z.request({
    url,
    method: METHOD,
    body: buildBody(bundle.inputData, bodyFields),
  });
  return response.data;
};

module.exports = {
  key: "product",
  noun: "Product",
  display: {
    label: "Create Product",
    description: "Create a product in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
