// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField, resolveMatterUid, setByPath } = require('../utils');

const PATH = "/business/payments/v1/products";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "product__cost",
    "path": [
      "product",
      "cost"
    ],
    "label": "Cost",
    "type": "number",
    "required": false,
    "isJson": false,
    "helpText": "Product cost"
  },
  {
    "key": "product__currency",
    "path": [
      "product",
      "currency"
    ],
    "label": "Currency",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Product currency"
  },
  {
    "key": "product__description",
    "path": [
      "product",
      "description"
    ],
    "label": "Description",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Product description"
  },
  {
    "key": "product__display",
    "path": [
      "product",
      "display"
    ],
    "label": "Display",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Display on products list. Default: true"
  },
  {
    "key": "product__image_url",
    "path": [
      "product",
      "image_url"
    ],
    "label": "Image Url",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Product image URL"
  },
  {
    "key": "product__name",
    "path": [
      "product",
      "name"
    ],
    "label": "Name",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Product name"
  },
  {
    "key": "product__price",
    "path": [
      "product",
      "price"
    ],
    "label": "Price",
    "type": "number",
    "required": true,
    "isJson": false,
    "helpText": "Product price"
  },
  {
    "key": "product__sku",
    "path": [
      "product",
      "sku"
    ],
    "label": "Sku",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Product SKU - must be unique per business"
  },
  {
    "key": "product__tax_ids",
    "path": [
      "product",
      "tax_ids"
    ],
    "label": "Tax Ids",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Product Tax IDs (JSON)"
  }
];
const pathFields = [];
// client_matter (D030): matter_uid is resolved from the chosen client (either a
// synthetic Client picker or an existing client_id field) and injected at these
// body paths. CLIENT_FIELD is the synthetic UI-only field (null when reusing a
// native client_id); CLIENT_SOURCE_KEY is the inputData key to resolve from.
const CLIENT_FIELD = null;
const CLIENT_SOURCE_KEY = null;
const MATTER_PATHS = [];

const inputFields = [
  ...pathFields,
  ...(CLIENT_FIELD ? [toInputField(CLIENT_FIELD)] : []),
  ...bodyFields.map(toInputField),
];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "uid": "sample-product-uid"
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const body = buildBody(bundle.inputData, bodyFields);
  if (CLIENT_SOURCE_KEY && MATTER_PATHS.length) {
    const matterUid = await resolveMatterUid(z, bundle, bundle.inputData[CLIENT_SOURCE_KEY]);
    if (CLIENT_FIELD && CLIENT_FIELD.required && !matterUid) {
      throw new z.errors.Error(
        'Could not find a matter for the selected client. Pick a client that has at least one matter.',
        'MatterNotFound'
      );
    }
    if (matterUid) for (const p of MATTER_PATHS) setByPath(body, p, matterUid);
  }
  const response = await z.request({ url, method: METHOD, body });
  return response.data;
};

module.exports = {
  key: "product",
  noun: "Product",
  display: {
    label: "Create Product",
    description: "Create a product in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
