// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField } = require('../utils');

const PATH = "/v2/settings/services";
const METHOD = "POST";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "name",
    "path": [
      "name"
    ],
    "label": "Name",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "Display name of the service (e.g., \"Executive Strategy Consultation\")."
  },
  {
    "key": "service_type",
    "path": [
      "service_type"
    ],
    "label": "Service Type",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "The kind of service to create. Use `appointment` for standard one-on-one services (default) or `event` for group events/workshops.",
    "choices": [
      "appointment",
      "event"
    ]
  },
  {
    "key": "duration",
    "path": [
      "duration"
    ],
    "label": "Duration",
    "type": "number",
    "required": true,
    "isJson": false,
    "helpText": "Duration of the service in minutes (e.g., 30, 45, 60)."
  },
  {
    "key": "charge_type",
    "path": [
      "charge_type"
    ],
    "label": "Charge Type",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "How the service is charged. `no_price` for free services, `paid` for priced services, `free` for explicitly free services.",
    "choices": [
      "no_price",
      "paid",
      "free"
    ]
  },
  {
    "key": "price",
    "path": [
      "price"
    ],
    "label": "Price",
    "type": "number",
    "required": false,
    "isJson": false,
    "helpText": "Price of the service in the smallest currency unit. Set to 0 for free services."
  },
  {
    "key": "currency",
    "path": [
      "currency"
    ],
    "label": "Currency",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "ISO 4217 currency code (e.g., \"USD\", \"EUR\")."
  },
  {
    "key": "interaction_type",
    "path": [
      "interaction_type"
    ],
    "label": "Interaction Type",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "How and where the service is delivered. Face-to-face types: `default_business_location` (uses the business address on file), `business_location` (custom address — provide in `meeting_interaction_details`), `client_location` (client provides location). Phone types: `business_phone` (provide number in `meeting_interaction_details`), `client_phone` (client provides number). Online types: `online` (provide URL in `meeting_interaction_details`), `zoom` (auto-generated Zoom link), `skype` (provide Skype name in `meeting_interaction_details`).",
    "choices": [
      "default_business_location",
      "business_location",
      "client_location",
      "business_phone",
      "client_phone",
      "online",
      "zoom",
      "skype"
    ]
  },
  {
    "key": "meeting_interaction_details",
    "path": [
      "meeting_interaction_details"
    ],
    "label": "Meeting Interaction Details",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "Location/contact details for the service. The meaning depends on `interaction_type`: address for `business_location`, phone number for `business_phone`, URL for `online`, Skype name for `skype`. Required when `interaction_type` is `business_location`, `business_phone`, `online`, or `skype`. Not needed for `default_business_location`, `client_location`, `client_phone`, or `zoom` (these are auto-resolved or client-provided)."
  },
  {
    "key": "description",
    "path": [
      "description"
    ],
    "label": "Description",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "A detailed description of the service shown to clients."
  },
  {
    "key": "display",
    "path": [
      "display"
    ],
    "label": "Display",
    "type": "boolean",
    "required": false,
    "isJson": false,
    "helpText": "Whether the service is visible in the client-facing booking page. Defaults to true."
  },
  {
    "key": "approval_mode",
    "path": [
      "approval_mode"
    ],
    "label": "Approval Mode",
    "type": "string",
    "required": false,
    "isJson": false,
    "helpText": "How bookings for this service are approved. `immediate` for auto-approval, `manual` for staff review.",
    "choices": [
      "immediate",
      "manual"
    ]
  },
  {
    "key": "staff_data",
    "path": [
      "staff_data"
    ],
    "label": "Staff Data",
    "type": "text",
    "required": false,
    "isJson": true,
    "helpText": "Array of staff assignment objects. Each object maps a staff member to this service. The booking system uses this to determine which staff members can offer this service — if omitted, no staff will be associated and booking attempts will fail with 'The provided staff member doesn't offer the provided service'. (JSON)"
  },
  {
    "key": "category__uid",
    "path": [
      "category",
      "uid"
    ],
    "label": "Uid",
    "type": "string",
    "required": true,
    "isJson": false,
    "helpText": "UID of an existing category. Can be obtained from GET /v2/settings/categories."
  }
];
const pathFields = [];

const inputFields = [...pathFields, ...bodyFields.map(toInputField)];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "uid": "sample-service-uid"
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const response = await z.request({
    url,
    method: METHOD,
    body: buildBody(bundle.inputData, bodyFields),
  });
  return response.data;
};

module.exports = {
  key: "service",
  noun: "Service",
  display: {
    label: "Create Service",
    description: "Create a service in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
