// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { buildBody, toInputField, resolveMatterUid, setByPath } = require('../utils');

const PATH = "/business/clients/v1/tags";
const METHOD = "PUT";
const PATH_PARAMS = [];

// Body field definitions (with internal path/isJson used to rebuild the body).
const bodyFields = [
  {
    "key": "tags",
    "path": [
      "tags"
    ],
    "label": "Tags",
    "type": "string",
    "required": true,
    "isJson": true,
    "helpText": "Tag strings to add, as a JSON array (e.g. [\"vip\",\"newsletter\"])."
  }
];
const pathFields = [];
// client_matter (D030): matter_uid is resolved from the chosen client (either a
// synthetic Client picker or an existing client_id field) and injected at these
// body paths. CLIENT_FIELD is the synthetic UI-only field (null when reusing a
// native client_id); CLIENT_SOURCE_KEY is the inputData key to resolve from.
const CLIENT_FIELD = {
  "key": "client_id",
  "label": "Client",
  "type": "string",
  "required": true,
  "dynamic": "list_clients.id.label",
  "helpText": "The client to tag — their matter is resolved automatically."
};
const CLIENT_SOURCE_KEY = "client_id";
const MATTER_PATHS = [];
// CLIENT_MATTER_ARRAY_PATH: when set, the resolved matter is injected here as a
// one-element array (e.g. ['matters','uids'] -> body.matters.uids = [matterUid]).
const CLIENT_MATTER_ARRAY_PATH = [
  "matters",
  "uids"
];
// QUERY: constant query params sent with the request (e.g. { new_api: true }).
const QUERY = null;
// Body shaping: WRAP_ARRAY wraps the built body as { [WRAP_ARRAY]: [body] };
// BODY_CONST merges constant keys at the top level (e.g. { new_api: true }).
const WRAP_ARRAY = null;
const BODY_CONST = {
  "new_api": true
};

const inputFields = [
  ...pathFields,
  ...(CLIENT_FIELD ? [toInputField(CLIENT_FIELD)] : []),
  ...bodyFields.map(toInputField),
];

// Static sample of the created record (D012). Reuses the linked trigger's real
// payload where the manifest pairs one; otherwise a minimal stub.
const sample = {
  "name": "jul",
  "business_id": 123,
  "clients": [
    "j9q05nvfv12w79vl",
    "k7zcc3nhb1aijzms"
  ]
};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    url = url.replace(`{${p}}`, encodeURIComponent(bundle.inputData[p]));
  }
  const body = buildBody(bundle.inputData, bodyFields);
  if (CLIENT_SOURCE_KEY && (MATTER_PATHS.length || CLIENT_MATTER_ARRAY_PATH)) {
    const matterUid = await resolveMatterUid(z, bundle, bundle.inputData[CLIENT_SOURCE_KEY]);
    if (CLIENT_FIELD && CLIENT_FIELD.required && !matterUid) {
      throw new z.errors.Error(
        'Could not find a matter for the selected client. Pick a client that has at least one matter.',
        'MatterNotFound'
      );
    }
    if (matterUid) {
      for (const p of MATTER_PATHS) setByPath(body, p, matterUid);
      if (CLIENT_MATTER_ARRAY_PATH) setByPath(body, CLIENT_MATTER_ARRAY_PATH, [matterUid]);
    }
  }
  let payload = body;
  if (WRAP_ARRAY) payload = { [WRAP_ARRAY]: [body], ...(BODY_CONST || {}) };
  else if (BODY_CONST) payload = { ...body, ...BODY_CONST };
  const request = { url, method: METHOD, body: payload };
  if (QUERY) request.params = QUERY;
  const response = await z.request(request);
  return response.data;
};

module.exports = {
  key: "tag_add",
  noun: "Tag",
  display: {
    label: "Add Tags to Client",
    description: "Create a tag in inTandem.",
  },
  operation: { inputFields, perform, sample },
};
