// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { unwrapWebhook } = require('../utils');

const EVENT = "client/updated";

const performSubscribe = async (z, bundle) => {
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/subscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: bundle.targetUrl },
  });
  return { ...(response.data || {}), event: EVENT, target_url: bundle.targetUrl };
};

const performUnsubscribe = async (z, bundle) => {
  const sub = bundle.subscribeData || {};
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/unsubscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: sub.target_url },
  });
  return response.data;
};

// Inbound webhook delivery: [{ entity_name, event_type, data }] -> data objects.
const perform = (z, bundle) => unwrapWebhook(bundle.cleanedRequest);

// No "recent events" endpoint exists, so the captured sample is the fallback
// users see when pulling a sample during Zap setup.
const sample = {
  "business_id": "s5ek7tfgp068i2st",
  "client_id": "k7zcc3nhb1aijzms",
  "first_name": "New",
  "last_name": "Client",
  "phone": "05544778899",
  "email": "user@email.com",
  "image": "http://www.meet2know.com/assets/img-avatar.gif",
  "address": {
    "main": "New York"
  },
  "custom_fields": {
    "Birthday": "1985-10-15"
  },
  "visible": true,
  "opt_in": null,
  "created_at": "2019-10-29T07:29:30Z",
  "updated_at": "2023-04-24T18:28:10.000+03:00",
  "spam": false
};
const performList = async () => [sample];

const outputFields = [
  {
    "key": "business_id",
    "label": "Business Id",
    "type": "string"
  },
  {
    "key": "client_id",
    "label": "Client Id",
    "type": "string"
  },
  {
    "key": "first_name",
    "label": "First Name",
    "type": "string"
  },
  {
    "key": "last_name",
    "label": "Last Name",
    "type": "string"
  },
  {
    "key": "phone",
    "label": "Phone",
    "type": "string"
  },
  {
    "key": "email",
    "label": "Email",
    "type": "string"
  },
  {
    "key": "image",
    "label": "Image",
    "type": "string"
  },
  {
    "key": "visible",
    "label": "Visible",
    "type": "boolean"
  },
  {
    "key": "opt_in",
    "label": "Opt In",
    "type": "string"
  },
  {
    "key": "created_at",
    "label": "Created At",
    "type": "string"
  },
  {
    "key": "updated_at",
    "label": "Updated At",
    "type": "string"
  },
  {
    "key": "spam",
    "label": "Spam",
    "type": "boolean"
  }
];

module.exports = {
  key: "client_updated",
  noun: "Client",
  display: {
    label: "New Client (Client/Updated)",
    description: "Triggers when an inTandem \"client/updated\" webhook fires.",
  },
  operation: {
    type: 'hook',
    performSubscribe,
    performUnsubscribe,
    perform,
    performList,
    sample,
    outputFields,
  },
};
