// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { unwrapWebhook } = require('../utils');

const EVENT = "estimate/requested";

const performSubscribe = async (z, bundle) => {
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/subscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: bundle.targetUrl },
  });
  return { ...(response.data || {}), event: EVENT, target_url: bundle.targetUrl };
};

const performUnsubscribe = async (z, bundle) => {
  const sub = bundle.subscribeData || {};
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/unsubscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: sub.target_url },
  });
  return response.data;
};

// Inbound webhook delivery: [{ entity_name, event_type, data }] -> data objects.
const perform = (z, bundle) => unwrapWebhook(bundle.cleanedRequest);

// No "recent events" endpoint exists, so the captured sample is the fallback
// users see when pulling a sample during Zap setup.
const sample = {
  "business_id": "s5ek7tfgp068i2st",
  "conversation_id": "l5718cwza39px7vj",
  "estimate_id": "50ic6dbp2wkntppt",
  "estimate_number": 1,
  "amount": "16.8",
  "currency": "ILS",
  "state": "issued",
  "due_date": "2019-11-29",
  "client_id": "54gjvtadfbxiom7y",
  "created_at": "2019-10-29T09:48:11.000+02:00"
};
const performList = async () => [sample];

const outputFields = [
  {
    "key": "business_id",
    "label": "Business Id",
    "type": "string"
  },
  {
    "key": "conversation_id",
    "label": "Conversation Id",
    "type": "string"
  },
  {
    "key": "estimate_id",
    "label": "Estimate Id",
    "type": "string"
  },
  {
    "key": "estimate_number",
    "label": "Estimate Number",
    "type": "number"
  },
  {
    "key": "amount",
    "label": "Amount",
    "type": "string"
  },
  {
    "key": "currency",
    "label": "Currency",
    "type": "string"
  },
  {
    "key": "state",
    "label": "State",
    "type": "string"
  },
  {
    "key": "due_date",
    "label": "Due Date",
    "type": "string"
  },
  {
    "key": "client_id",
    "label": "Client Id",
    "type": "string"
  },
  {
    "key": "created_at",
    "label": "Created At",
    "type": "string"
  }
];

module.exports = {
  key: "estimate_requested",
  noun: "Estimate",
  display: {
    label: "New Estimate (estimate/requested)",
    description: "Triggers when an inTandem \"estimate/requested\" webhook fires.",
  },
  operation: {
    type: 'hook',
    performSubscribe,
    performUnsubscribe,
    perform,
    performList,
    sample,
    outputFields,
  },
};
