// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { getByPath, resolveBusinessUid } = require('../utils');

const PATH = "/platform/v1/businesses/{business_uid}/staffs";
const PATH_PARAMS = [
  "business_uid"
];
const ARRAY_PATH = "data.staff";
const ID_FIELD = "id";
const LABEL_FIELDS = [
  "display_name"
];
const QUERY = {};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    // business_uid is auto-resolved from the token's business; other path params
    // come from auth data. If it can't be resolved, return no options instead
    // of erroring.
    const value = p === 'business_uid' ? await resolveBusinessUid(z, bundle) : bundle.authData && bundle.authData[p];
    if (!value) return [];
    url = url.replace(`{${p}}`, encodeURIComponent(value));
  }
  const response = await z.request({ url, method: 'GET', params: QUERY });
  const list = getByPath(response.data, ARRAY_PATH) || [];
  return list.map((item) => ({
    ...item,
    id: item[ID_FIELD],
    label: LABEL_FIELDS.map((f) => item[f]).filter(Boolean).join(' ') || String(item[ID_FIELD]),
  }));
};

module.exports = {
  key: "list_staff",
  noun: "Staff",
  display: {
    label: "List Staffs",
    description: "Internal: lists staffs to populate dynamic dropdowns.",
    hidden: true,
  },
  operation: { perform, canPaginate: true },
};
