// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { getByPath, resolveBusinessUid } = require('../utils');

const PATH = "/v2/settings/categories";
const PATH_PARAMS = [];
const ARRAY_PATH = "";
const ID_FIELD = "uid";
const LABEL_FIELDS = [
  "name"
];
const QUERY = {};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    // business_uid is auto-resolved from the token's business; other path params
    // come from auth data. If it can't be resolved, return no options instead
    // of erroring.
    const value = p === 'business_uid' ? await resolveBusinessUid(z, bundle) : bundle.authData && bundle.authData[p];
    if (!value) return [];
    url = url.replace(`{${p}}`, encodeURIComponent(value));
  }
  // Resolve {business_uid} placeholders in query params from the token's business
  // (some list endpoints require business_id as a query param, not a path param).
  const params = { ...QUERY };
  for (const k of Object.keys(params)) {
    if (params[k] === '{business_uid}') {
      const biz = await resolveBusinessUid(z, bundle);
      if (!biz) return [];
      params[k] = biz;
    }
  }
  const response = await z.request({ url, method: 'GET', params });
  const list = getByPath(response.data, ARRAY_PATH) || [];
  return list.map((item) => ({
    ...item,
    id: item[ID_FIELD],
    label: LABEL_FIELDS.map((f) => item[f]).filter(Boolean).join(' ') || String(item[ID_FIELD]),
  }));
};

module.exports = {
  key: "list_service_categories",
  noun: "Service Category",
  display: {
    label: "List Service Categorys",
    description: "Internal: lists service categorys to populate dynamic dropdowns.",
    hidden: true,
  },
  operation: { perform, canPaginate: true },
};
