// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { getByPath } = require('../utils');

const PATH = "/platform/v1/clients";
const PATH_PARAMS = [];
const ARRAY_PATH = "data.clients";
const ID_FIELD = "id";
const LABEL_FIELDS = [
  "first_name",
  "last_name"
];
const QUERY = {};

const perform = async (z, bundle) => {
  let url = `${BASE_URL}${PATH}`;
  for (const p of PATH_PARAMS) {
    // Path params (e.g. {business_uid}) are sourced from the connection's auth
    // data. If absent, we can't list — return no options rather than erroring.
    const value = bundle.authData && bundle.authData[p];
    if (!value) return [];
    url = url.replace(`{${p}}`, encodeURIComponent(value));
  }
  const response = await z.request({ url, method: 'GET', params: QUERY });
  const list = getByPath(response.data, ARRAY_PATH) || [];
  return list.map((item) => ({
    ...item,
    id: item[ID_FIELD],
    label: LABEL_FIELDS.map((f) => item[f]).filter(Boolean).join(' ') || String(item[ID_FIELD]),
  }));
};

module.exports = {
  key: "list_clients",
  noun: "Client",
  display: {
    label: "List Clients",
    description: "Internal: lists clients to populate dynamic dropdowns.",
    hidden: true,
  },
  operation: { perform, canPaginate: true },
};
