// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { getByPath } = require('../utils');

const PATH = "/platform/v1/services";
const ARRAY_PATH = "data.services";
const ID_FIELD = "id";
const LABEL_FIELDS = [
  "name"
];
const QUERY = {};

const perform = async (z, bundle) => {
  const response = await z.request({ url: `${BASE_URL}${PATH}`, method: 'GET', params: QUERY });
  const list = getByPath(response.data, ARRAY_PATH) || [];
  return list.map((item) => ({
    ...item,
    id: item[ID_FIELD],
    label: LABEL_FIELDS.map((f) => item[f]).filter(Boolean).join(' ') || String(item[ID_FIELD]),
  }));
};

module.exports = {
  key: "list_services",
  noun: "Service",
  display: {
    label: "List Services",
    description: "Internal: lists services to populate dynamic dropdowns.",
    hidden: true,
  },
  operation: { perform, canPaginate: true },
};
