// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { unwrapWebhook } = require('../utils');

const EVENT = "message/client_sent_message";

const performSubscribe = async (z, bundle) => {
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/subscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: bundle.targetUrl },
  });
  return { ...(response.data || {}), event: EVENT, target_url: bundle.targetUrl };
};

const performUnsubscribe = async (z, bundle) => {
  const sub = bundle.subscribeData || {};
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/unsubscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: sub.target_url },
  });
  return response.data;
};

// Inbound webhook delivery: [{ entity_name, event_type, data }] -> data objects.
const perform = (z, bundle) => unwrapWebhook(bundle.cleanedRequest);

// No "recent events" endpoint exists, so the captured sample is the fallback
// users see when pulling a sample during Zap setup.
const sample = {
  "business_id": "s5ek7tfgp068i2st",
  "staff_id": "e6j4i1ofy2pf0dmg",
  "conversation_id": "pto6yng4e908c8g0",
  "message_id": "fjo0q77g2a4hmotc",
  "message": "Thank you for your message",
  "client_id": "54gjvtadfbxiom7y",
  "created_at": "2019-10-29T09:36:59.105+02:00"
};
const performList = async () => [sample];

const outputFields = [
  {
    "key": "business_id",
    "label": "Business Id",
    "type": "string"
  },
  {
    "key": "staff_id",
    "label": "Staff Id",
    "type": "string"
  },
  {
    "key": "conversation_id",
    "label": "Conversation Id",
    "type": "string"
  },
  {
    "key": "message_id",
    "label": "Message Id",
    "type": "string"
  },
  {
    "key": "message",
    "label": "Message",
    "type": "string"
  },
  {
    "key": "client_id",
    "label": "Client Id",
    "type": "string"
  },
  {
    "key": "created_at",
    "label": "Created At",
    "type": "string"
  }
];

module.exports = {
  key: "message_client_sent_message",
  noun: "Message",
  display: {
    label: "New Message (Message/Client_Sent_Message)",
    description: "Triggers when an inTandem \"message/client_sent_message\" webhook fires.",
  },
  operation: {
    type: 'hook',
    performSubscribe,
    performUnsubscribe,
    perform,
    performList,
    sample,
    outputFields,
  },
};
