// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { unwrapWebhook } = require('../utils');

const EVENT = "payment/recorded";

const performSubscribe = async (z, bundle) => {
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/subscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: bundle.targetUrl },
  });
  return { ...(response.data || {}), event: EVENT, target_url: bundle.targetUrl };
};

const performUnsubscribe = async (z, bundle) => {
  const sub = bundle.subscribeData || {};
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/unsubscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: sub.target_url },
  });
  return response.data;
};

// Inbound webhook delivery: [{ entity_name, event_type, data }] -> data objects.
const perform = (z, bundle) => unwrapWebhook(bundle.cleanedRequest);

// No "recent events" endpoint exists, so the captured sample is the fallback
// users see when pulling a sample during Zap setup.
const sample = {
  "payment_id": "i80jmue5khmm89mt",
  "business_id": "s36f9j76o95dclwn",
  "conversation_id": "9og26xm7z6vi9hsj",
  "state": "paid",
  "title": "INVOICE #0000011",
  "note": null,
  "amount": 333,
  "currency": "USD",
  "charge_at": "2022-02-06T12:01:35.000Z",
  "refunded_at": null,
  "payment_method": "Bank Transfer",
  "other_payment_method": null,
  "reference": null,
  "offline": true,
  "pay_key": null,
  "payment_request_id": "swv4y4ecobe9s204",
  "payment_requests": [
    {
      "type": "Invoice",
      "id": "zup98lxfmm1aagtk"
    }
  ],
  "client_id": "pnm372tuy83p24f0",
  "created_at": "2022-02-06T12:01:51.000Z"
};
const performList = async () => [sample];

const outputFields = [
  {
    "key": "payment_id",
    "label": "Payment Id",
    "type": "string"
  },
  {
    "key": "business_id",
    "label": "Business Id",
    "type": "string"
  },
  {
    "key": "conversation_id",
    "label": "Conversation Id",
    "type": "string"
  },
  {
    "key": "state",
    "label": "State",
    "type": "string"
  },
  {
    "key": "title",
    "label": "Title",
    "type": "string"
  },
  {
    "key": "note",
    "label": "Note",
    "type": "string"
  },
  {
    "key": "amount",
    "label": "Amount",
    "type": "number"
  },
  {
    "key": "currency",
    "label": "Currency",
    "type": "string"
  },
  {
    "key": "charge_at",
    "label": "Charge At",
    "type": "string"
  },
  {
    "key": "refunded_at",
    "label": "Refunded At",
    "type": "string"
  },
  {
    "key": "payment_method",
    "label": "Payment Method",
    "type": "string"
  },
  {
    "key": "other_payment_method",
    "label": "Other Payment Method",
    "type": "string"
  },
  {
    "key": "reference",
    "label": "Reference",
    "type": "string"
  },
  {
    "key": "offline",
    "label": "Offline",
    "type": "boolean"
  },
  {
    "key": "pay_key",
    "label": "Pay Key",
    "type": "string"
  },
  {
    "key": "payment_request_id",
    "label": "Payment Request Id",
    "type": "string"
  },
  {
    "key": "client_id",
    "label": "Client Id",
    "type": "string"
  },
  {
    "key": "created_at",
    "label": "Created At",
    "type": "string"
  }
];

module.exports = {
  key: "payment_recorded",
  noun: "Payment",
  display: {
    label: "New Payment (Payment/Recorded)",
    description: "Triggers when an inTandem \"payment/recorded\" webhook fires.",
  },
  operation: {
    type: 'hook',
    performSubscribe,
    performUnsubscribe,
    perform,
    performList,
    sample,
    outputFields,
  },
};
