// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { unwrapWebhook } = require('../utils');

const EVENT = "service/updated";

const performSubscribe = async (z, bundle) => {
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/subscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: bundle.targetUrl },
  });
  return { ...(response.data || {}), event: EVENT, target_url: bundle.targetUrl };
};

const performUnsubscribe = async (z, bundle) => {
  const sub = bundle.subscribeData || {};
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/unsubscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: sub.target_url },
  });
  return response.data;
};

// Inbound webhook delivery: [{ entity_name, event_type, data }] -> data objects.
const perform = (z, bundle) => unwrapWebhook(bundle.cleanedRequest);

// No "recent events" endpoint exists, so the captured sample is the fallback
// users see when pulling a sample during Zap setup.
const sample = {
  "uid": "jy6hpuy25g0n83oa",
  "name": "my availability service",
  "type": "AppointmentService",
  "image_path": null,
  "interaction_type": "default_business_location",
  "duration": 75,
  "min_hours_before_meeting": 72,
  "padding": 20,
  "future_bookings_limit": 60,
  "interval": 20,
  "price": null,
  "meeting_length": 75,
  "charge_type": "no_price",
  "active": true,
  "max_attendance": null,
  "currency": "ILS",
  "business_uid": "k5lh1ri2rygw6nnp",
  "updated_at": "2024-03-19T11:35:59.000+02:00"
};
const performList = async () => [sample];

const outputFields = [
  {
    "key": "uid",
    "label": "Uid",
    "type": "string"
  },
  {
    "key": "name",
    "label": "Name",
    "type": "string"
  },
  {
    "key": "type",
    "label": "Type",
    "type": "string"
  },
  {
    "key": "image_path",
    "label": "Image Path",
    "type": "string"
  },
  {
    "key": "interaction_type",
    "label": "Interaction Type",
    "type": "string"
  },
  {
    "key": "duration",
    "label": "Duration",
    "type": "number"
  },
  {
    "key": "min_hours_before_meeting",
    "label": "Min Hours Before Meeting",
    "type": "number"
  },
  {
    "key": "padding",
    "label": "Padding",
    "type": "number"
  },
  {
    "key": "future_bookings_limit",
    "label": "Future Bookings Limit",
    "type": "number"
  },
  {
    "key": "interval",
    "label": "Interval",
    "type": "number"
  },
  {
    "key": "price",
    "label": "Price",
    "type": "string"
  },
  {
    "key": "meeting_length",
    "label": "Meeting Length",
    "type": "number"
  },
  {
    "key": "charge_type",
    "label": "Charge Type",
    "type": "string"
  },
  {
    "key": "active",
    "label": "Active",
    "type": "boolean"
  },
  {
    "key": "max_attendance",
    "label": "Max Attendance",
    "type": "string"
  },
  {
    "key": "currency",
    "label": "Currency",
    "type": "string"
  },
  {
    "key": "business_uid",
    "label": "Business Uid",
    "type": "string"
  },
  {
    "key": "updated_at",
    "label": "Updated At",
    "type": "string"
  }
];

module.exports = {
  key: "service_updated",
  noun: "Service",
  display: {
    label: "New Service (Service/Updated)",
    description: "Triggers when an inTandem \"service/updated\" webhook fires.",
  },
  operation: {
    type: 'hook',
    performSubscribe,
    performUnsubscribe,
    perform,
    performList,
    sample,
    outputFields,
  },
};
