// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const { BASE_URL } = require('../constants');
const { unwrapWebhook } = require('../utils');

const EVENT = "tag/add";

const performSubscribe = async (z, bundle) => {
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/subscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: bundle.targetUrl },
  });
  return { ...(response.data || {}), event: EVENT, target_url: bundle.targetUrl };
};

const performUnsubscribe = async (z, bundle) => {
  const sub = bundle.subscribeData || {};
  const response = await z.request({
    url: `${BASE_URL}/platform/v1/webhook/unsubscribe`,
    method: 'POST',
    body: { event: EVENT, target_url: sub.target_url },
  });
  return response.data;
};

// Inbound webhook delivery: [{ entity_name, event_type, data }] -> data objects.
const perform = (z, bundle) => unwrapWebhook(bundle.cleanedRequest);

// No "recent events" endpoint exists, so the captured sample is the fallback
// users see when pulling a sample during Zap setup.
const sample = {
  "name": "jul",
  "business_id": 123,
  "clients": [
    "j9q05nvfv12w79vl",
    "k7zcc3nhb1aijzms"
  ]
};
const performList = async () => [sample];

const outputFields = [
  {
    "key": "name",
    "label": "Name",
    "type": "string"
  },
  {
    "key": "business_id",
    "label": "Business Id",
    "type": "number"
  }
];

module.exports = {
  key: "tag_add",
  noun: "Tag",
  display: {
    label: "New Tag (Tag/Add)",
    description: "Triggers when an inTandem \"tag/add\" webhook fires.",
  },
  operation: {
    type: 'hook',
    performSubscribe,
    performUnsubscribe,
    perform,
    performList,
    sample,
    outputFields,
  },
};
