// GENERATED by scripts/generate-zapier.js — do not edit by hand.
const authentication = require('./authentication');
const { includeBearerToken, checkForErrors } = require('./middleware');

const triggers = {
  "client_updated": require('./triggers/client_updated'),
  "invoice_issued": require('./triggers/invoice_issued'),
  "payment_recorded": require('./triggers/payment_recorded'),
  "estimate_requested": require('./triggers/estimate_requested'),
  "appointment_scheduled": require('./triggers/appointment_scheduled'),
  "appointment_cancelled": require('./triggers/appointment_cancelled'),
  "service_updated": require('./triggers/service_updated'),
  "list_clients": require('./triggers/list_clients'),
  "list_services": require('./triggers/list_services'),
  "list_estimates": require('./triggers/list_estimates'),
  "list_staff": require('./triggers/list_staff'),
  "list_service_categories": require('./triggers/list_service_categories'),
};

const creates = {
  "client": require('./creates/client'),
  "client_note": require('./creates/client_note'),
  "invoice": require('./creates/invoice'),
  "estimate": require('./creates/estimate'),
  "payment": require('./creates/payment'),
  "lead": require('./creates/lead'),
  "booking": require('./creates/booking'),
  "product": require('./creates/product'),
  "service": require('./creates/service'),
};

module.exports = {
  version: require('./package.json').version,
  platformVersion: require('zapier-platform-core').version,
  authentication,
  beforeRequest: [includeBearerToken],
  afterResponse: [checkForErrors],
  // Don't auto-clean input data — keep what the user maps predictable (D028).
  flags: { cleanInputData: false },
  triggers,
  creates,
};
